# Generated by Django 5.2.9 on 2025-12-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
