# Generated by Django 5.2.9 on 2025-12-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=40),
            preserve_default=False,
        ),
    ]
