# Generated by Django 5.2.9 on 2025-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='creditos',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
