# Generated by Django 5.2.9 on 2025-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usuario_creditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField()),
                ('passWord', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Produto',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagem',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='preco',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantidade',
            new_name='quantity',
        ),
    ]
