# Generated by Django 5.2.9 on 2025-12-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_rename_produto_product_delete_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passWord',
            new_name='password',
        ),
    ]
